import 'dart:convert';
import 'dart:io';

/// Converts the const map in lib/shared/i18n/app_strings.dart into
/// lib/l10n/app_en.arb + lib/l10n/app_it.arb.
void main(List<String> args) {
  final root = args.isEmpty ? '.' : args[0];
  final src = File('$root/lib/shared/i18n/app_strings.dart').readAsStringSync();
  final start = src.indexOf('_values = {');
  if (start < 0) throw StateError('map not found');
  var i = src.indexOf('{', start);

  final entries = <String, Map<String, String>>{};
  i++; // past outer {
  while (true) {
    i = _skipWs(src, i);
    if (src[i] == '}') break;
    final key = _readString(src, i);
    i = key.end;
    i = _skipWs(src, i);
    if (src[i] != ':') throw StateError('expected : at $i');
    i = _skipWs(src, i + 1);
    if (src[i] != '{') throw StateError('expected { at $i');
    i++;
    final inner = <String, String>{};
    while (true) {
      i = _skipWs(src, i);
      if (src[i] == '}') {
        i++;
        break;
      }
      final lang = _readString(src, i);
      i = _skipWs(src, lang.end);
      if (src[i] != ':') throw StateError('expected : at $i');
      i = _skipWs(src, i + 1);
      final val = _readString(src, i);
      i = _skipWs(src, val.end);
      inner[lang.value] = val.value;
      if (src[i] == ',') i++;
    }
    entries[key.value] = inner;
    i = _skipWs(src, i);
    if (src[i] == ',') i++;
  }

  final placeholderRe = RegExp(r'\{([a-zA-Z_][a-zA-Z0-9_]*)\}');
  final en = <String, dynamic>{'@@locale': 'en'};
  final it = <String, dynamic>{'@@locale': 'it'};
  final seen = <String, String>{};

  for (final e in entries.entries) {
    final name = _camel(e.key);
    if (seen.containsKey(name)) {
      throw StateError('camelCase collision: ${e.key} vs ${seen[name]}');
    }
    seen[name] = e.key;
    final enVal = e.value['en'] ?? e.value.values.first;
    final itVal = e.value['it'] ?? enVal;
    en[name] = _escapeIcu(enVal);
    it[name] = _escapeIcu(itVal);
    final names = <String>{
      ...placeholderRe.allMatches(enVal).map((m) => m.group(1)!),
      ...placeholderRe.allMatches(itVal).map((m) => m.group(1)!),
    };
    final meta = <String, dynamic>{'description': 'Migrated from ${e.key}'};
    if (names.isNotEmpty) {
      meta['placeholders'] = {
        for (final n in names) n: {'type': 'String'},
      };
    }
    en['@$name'] = meta;
  }

  // --- ICU plural demo keys: not expressible with the const map ---
  const pluralKeys = <String, List<String>>{
    'setsCompletedCount': [
      '{count, plural, =0{No sets completed} =1{1 set completed} other{{count} sets completed}}',
      '{count, plural, =0{Nessuna serie completata} =1{1 serie completata} other{{count} serie completate}}',
    ],
    'exercisesInWorkoutCount': [
      '{count, plural, =0{No exercises} =1{1 exercise} other{{count} exercises}}',
      '{count, plural, =0{Nessun esercizio} =1{1 esercizio} other{{count} esercizi}}',
    ],
  };
  for (final e in pluralKeys.entries) {
    en[e.key] = e.value[0];
    it[e.key] = e.value[1];
    en['@${e.key}'] = {
      'description': 'ICU plural example',
      'placeholders': {
        'count': {'type': 'int'},
      },
    };
  }

  const enc = JsonEncoder.withIndent('  ');
  Directory('$root/lib/l10n').createSync(recursive: true);
  File('$root/lib/l10n/app_en.arb').writeAsStringSync('${enc.convert(en)}\n');
  File('$root/lib/l10n/app_it.arb').writeAsStringSync('${enc.convert(it)}\n');
  // --- bridge: dotted legacy key -> generated AppLocalizations member ---
  final b = StringBuffer()
    ..writeln('// GENERATED - do not edit by hand.')
    ..writeln('// Maps the legacy dotted keys of AppStrings to the members')
    ..writeln('// generated by gen_l10n from lib/l10n/app_en.arb.')
    ..writeln("import 'package:coachly/l10n/app_localizations.dart';")
    ..writeln()
    ..writeln('typedef ArbResolver =')
    ..writeln(
      '    String Function(AppLocalizations l10n, Map<String, String> params);',
    )
    ..writeln()
    ..writeln(
      'final Map<String, ArbResolver> arbBridge = <String, ArbResolver>{',
    );
  for (final e in entries.entries) {
    final name = _camel(e.key);
    final meta = en['@$name'] as Map<String, dynamic>;
    final ph = (meta['placeholders'] as Map<String, dynamic>?)?.keys.toList();
    final legacy = e.key.replaceAll(r'$', r'\$');
    if (ph == null || ph.isEmpty) {
      b.writeln("  '$legacy': (l10n, _) => l10n.$name,");
    } else {
      final args = ph.map((p) => "params['$p'] ?? ''").join(', ');
      b.writeln("  '$legacy': (l10n, params) => l10n.$name($args),");
    }
  }
  b.writeln('};');
  File('$root/lib/shared/i18n/arb_bridge.dart').writeAsStringSync(b.toString());

  stdout.writeln('converted ${entries.length} keys');
}

final _phRe = RegExp(r'\{[a-zA-Z_][a-zA-Z0-9_]*\}');

/// Escapes ICU metacharacters (`{`, `}`, `'`) outside placeholders, as
/// required by `use-escaping: true` in l10n.yaml.
String _escapeIcu(String value) {
  final buf = StringBuffer();
  var last = 0;
  void literal(String chunk) {
    for (final ch in chunk.split('')) {
      buf.write(switch (ch) {
        "'" => "''",
        '{' => "'{'",
        '}' => "'}'",
        _ => ch,
      });
    }
  }

  for (final m in _phRe.allMatches(value)) {
    literal(value.substring(last, m.start));
    buf.write(m.group(0));
    last = m.end;
  }
  literal(value.substring(last));
  return buf.toString();
}

int _skipWs(String s, int i) {
  while (i < s.length) {
    final c = s[i];
    if (c == ' ' || c == '\n' || c == '\r' || c == '\t') {
      i++;
    } else if (c == '/' && i + 1 < s.length && s[i + 1] == '/') {
      while (i < s.length && s[i] != '\n') {
        i++;
      }
    } else {
      break;
    }
  }
  return i;
}

class _Str {
  final String value;
  final int end;
  _Str(this.value, this.end);
}

_Str _readString(String s, int i) {
  final quote = s[i];
  if (quote != "'" && quote != '"') {
    throw StateError('expected quote at $i, found ${s.substring(i, i + 20)}');
  }
  final buf = StringBuffer();
  i++;
  while (s[i] != quote) {
    if (s[i] == r'\') {
      final n = s[i + 1];
      buf.write(switch (n) {
        'n' => '\n',
        't' => '\t',
        _ => n,
      });
      i += 2;
    } else {
      buf.write(s[i]);
      i++;
    }
  }
  // handle adjacent string literal concatenation
  var j = _skipWs(s, i + 1);
  if (j < s.length && (s[j] == "'" || s[j] == '"')) {
    final next = _readString(s, j);
    return _Str(buf.toString() + next.value, next.end);
  }
  return _Str(buf.toString(), i + 1);
}

String _camel(String key) {
  final parts = key.split(RegExp(r'[._]+')).where((p) => p.isNotEmpty).toList();
  final buf = StringBuffer();
  for (var k = 0; k < parts.length; k++) {
    final p = parts[k];
    if (k == 0) {
      buf.write(p[0].toLowerCase() + p.substring(1));
    } else {
      buf.write(p[0].toUpperCase() + p.substring(1));
    }
  }
  return buf.toString();
}
